#!/usr/bin/env bash
# Bash script to display a list of currently running processes
#Must show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy

ps aux
