#!/usr/bin/env bash
# Bash script to display the content of /etc/passwd

while IFS=':' read -r username x userid x x x homedir x
do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $homedir"
done < /etc/passwd
