#!/usr/bin/env bash
# This script displays "Best School" 10 times with a "Hi" message at the end

count=0
while [ $count -lt 10 ]
do
  echo "Best School"
  count=$((count+1))
done

if [ $count -eq 10 ]
then
  echo "Hi"
fi

