#!/usr/bin/env bash
# This script displays "Best School" for most iterations, "Bad luck" for the 4th iteration, and "Good luck" for the 8th iteration

count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "Bad luck"
  elif [ $count -eq 8 ]
  then
    echo "Good luck"
  else
    echo "Best School"
  fi
  count=$((count+1))
done

